//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DIADIEM_TOUR
    {
        public int ID_CT_DIADIEM_TOUR { get; set; }
        public int IDDIADIEM { get; set; }
        public int IDTOUR { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
        public virtual TOUR TOUR { get; set; }
    }
}
