//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DOAN_PHUONGTIEN
    {
        public int IDCT { get; set; }
        public Nullable<int> IDDOAN { get; set; }
        public Nullable<int> IDPT { get; set; }
        public string CHIPHIPT { get; set; }
    
        public virtual DOAN DOAN { get; set; }
        public virtual PHUONGTIEN PHUONGTIEN { get; set; }
    }
}
