//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DOAN_CHIPHIKHAC
    {
        public int IDCT { get; set; }
        public int IDDOAN { get; set; }
        public string CHIPHI { get; set; }
        public string MOTA { get; set; }
    
        public virtual DOAN DOAN { get; set; }
    }
}
