//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOAN()
        {
            this.CT_DOAN_KHACHHANG = new HashSet<CT_DOAN_KHACHHANG>();
            this.CT_DOAN_KHACHSAN = new HashSet<CT_DOAN_KHACHSAN>();
            this.CT_DOAN_PHUONGTIEN = new HashSet<CT_DOAN_PHUONGTIEN>();
        }
    
        public int IDDOAN { get; set; }
        public string TENDOAN { get; set; }
        public int IDTOUR { get; set; }
        public int SOLUONGKH { get; set; }
        public string NGAYBATDAU { get; set; }
        public string NGAYKETTHUC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DOAN_KHACHHANG> CT_DOAN_KHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DOAN_KHACHSAN> CT_DOAN_KHACHSAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DOAN_PHUONGTIEN> CT_DOAN_PHUONGTIEN { get; set; }
        public virtual TOUR TOUR { get; set; }
    }
}
