//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUONGTIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHUONGTIEN()
        {
            this.CT_DOAN_PHUONGTIEN = new HashSet<CT_DOAN_PHUONGTIEN>();
        }
    
        public int IDPT { get; set; }
        public string LOAIPT { get; set; }
        public Nullable<int> SOGHE { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<bool> ISAVAILABLE { get; set; }
        public string BKS { get; set; }
        public Nullable<bool> BELONGTOCOMPANY { get; set; }
        public string GIATHUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DOAN_PHUONGTIEN> CT_DOAN_PHUONGTIEN { get; set; }
    }
}
